name: project15_mof_stability
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - lightgbm
  - optuna
  - joblib
  - openpyxl
  - jupyter
  - notebook
  - pip
